package com.ecommerce.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Product Entity - JPA Entity representing a product in the database
 * 
 * WHAT IT DOES:
 * - Maps to "products" table in MySQL database
 * - Represents a single product with all its attributes
 * - Used by JPA/Hibernate to perform database operations
 * 
 * FLOW:
 * 1. Entity class defines table structure
 * 2. JPA creates/updates "products" table based on this entity
 * 3. Service layer uses this entity to save/retrieve products
 * 4. Entity is converted to DTO for API responses
 * 
 * ANNOTATIONS:
 * - @Entity: Marks this as a JPA entity (database table)
 * - @Table: Specifies table name in database
 * - @Data: Lombok generates getters, setters, toString, equals, hashCode
 * - @NoArgsConstructor: Lombok generates no-args constructor
 * - @AllArgsConstructor: Lombok generates constructor with all fields
 */
@Entity
@Table(name = "products")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Product {
    /**
     * Primary key - Unique identifier for each product
     * Auto-generated by database (AUTO_INCREMENT in MySQL)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Product name - Required field, cannot be null
     * Example: "Laptop", "Smartphone", "Headphones"
     */
    @Column(nullable = false)
    private String name;

    /**
     * Product description - Optional field
     * Uses TEXT column type to allow long descriptions
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * Product price - Required field, stored as BigDecimal for precision
     * Example: 99.99, 1299.00
     */
    @Column(nullable = false)
    private BigDecimal price;

    /**
     * Image URL - URL of product image stored in Cloudinary
     * Example: "https://res.cloudinary.com/cloudname/image/upload/v123/image.jpg"
     */
    @Column(name = "image_url")
    private String imageUrl;

    /**
     * Stock quantity - Number of items available in inventory
     * Default value: 0 (out of stock)
     */
    @Column(name = "stock_quantity")
    private Integer stockQuantity = 0;

    /**
     * Product category - Optional categorization
     * Example: "Electronics", "Clothing", "Books"
     */
    @Column(name = "category")
    private String category;

    /**
     * Seller ID - Links product to the seller who created it
     * Nullable: Admin can create products without seller
     * When seller creates product, this is set to their user ID
     */
    @Column(name = "seller_id")
    private Long sellerId;
}

